name = "SwitchingAnalysis"
uuid = "03d4aadf-90ee-46bb-9184-4e203bdec9f1"
authors = ["DarioSarra"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
